'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DisplayRecipe
    
    '''<summary>
    '''ErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''DisplayTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''ltRecipeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltRecipeName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltOwner As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltSubmissionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltSubmissionDate As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltRating As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''hypReadReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypReadReviews As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''imgRecipeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRecipeImage As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ltRecipeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltRecipeDescription As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltServingSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltServingSize As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnServingSizeAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServingSizeAdjustment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlIngredients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIngredients As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInstructions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReview As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
End Class
