'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PanelControl
    
    '''<summary>
    '''SuccessMessagePlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''tblDirections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDirections As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''btnAddStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStep As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlDirections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDirections As Global.System.Web.UI.WebControls.Panel
End Class
